### ISSUE TITLE
Server discoverable via server browser, but doesn't respond

### ISSUE THREAD

**Issue by Fynf** [avivace/ror2-server#14]
Using the command 
`docker run -p 27016:27016/udp -e R2_HOSTNAME='Server-Name' -e R2_PSW='Password' -e R2_HEARTBEAT=1 avivace/ror2server:latest`
the server becomes discoverable via the games internal server browser like it's intended, but once you try to connect to the server, either via the GUI or the developer console, the server simply doesn't reply.

When calling Steam, the API returns:
`{"response":{"success":true,"servers":[{"addr":"<IP-ADDRESS>:27016","gmsindex":65534,"appid":632360,"gamedir":"Risk of Rain 2","region":-1,"secure":true,"lan":false,"gameport":27015,"specport":0}]}}`

Both UDP-Ports 27015 and 27016 are open in the firewall, so I'm a bit stumped as to why the server is able to announce itself to steam, but then unable to respond to clients trying to connect.

**Comment by dubvulture** [comment]
You didn't forward the 27015 port as you did for the 27016 in the `docker run` command.

**Comment by Fynf** [comment]
Oh,oops. Thanks for the lightning fast reply!

`docker run -p 27016:27016/udp -p 27015:27015/udp -e R2_HOSTNAME='Server-Name' -e R2_PSW='Password' -e R2_HEARTBEAT=1 avivace/ror2server:latest`

made it work. Thanks again!
