### ISSUE TITLE
Server seems stuck on one processor/is not using all resources

### ISSUE THREAD

**Issue by Binary-2** [avivace/ror2-server#15]
Mild speculation on my end, but even with a docker container with unlimited resources, my server will begin to lag as soon as a moderate number of enemies begin to fill the map.

Network ping does not seem to be a factor, and here are some resource stats from portainer and htop:
![image](https://user-images.githubusercontent.com/38906390/95609350-67f99b80-0a13-11eb-9121-9cd9cff9bf47.png)
![image](https://user-images.githubusercontent.com/38906390/95609367-6c25b900-0a13-11eb-921a-991e70e64d3b.png)

It's entirely possible I'm running ancient hardware and I've ordered more modern processors even, but I'm not sure where to begin helping debugging this issue

**Comment by Binary-2** [comment]
Here's a pastebin of the server's logs. I've noticed a few issues but the server's been running smoothly and people don't have much issues playing so I haven't payed much attention to them.

https://pastebin.com/mvAGUrpL

**Comment by Binary-2** [comment]
![image](https://user-images.githubusercontent.com/38906390/95714292-da899780-0c1c-11eb-9c11-6659c877bebf.png)

After leaving it to run overnight, it'll constantly be found like this, but I'm not certain what the issue is? Does this just happen after a certain number of loops?

**Comment by dubvulture** [comment]
The real question is: does it also happen natively on Windows? If so, hopoo pls fix.

**Comment by Binary-2** [comment]
I figured out this state can also be reached by the server trying to load a map without any players.

If a player leaves the game right before or during a map changes and the server is now empty, it'll fail to realize the server is in an empty state.

**Comment by avivace** [comment]
I'm not sure, but I think @InfernalPlacebo / his group patches the executables for this behaviour?

**Comment by Binary-2** [comment]
Possible, I tried adding a GPU to my server hardware and it runs much better now. Risk of Rain 2 itself just wants to use a GPU most of all I guess.
