### ISSUE TITLE
Null Reference Exception, can't connect to server

### ISSUE THREAD

**Issue by tgkenney** [avivace/ror2-server#20]
I'm trying to run this container on a CentOS headless virtual machine.  I initially tried running the container using docker compose, but when that I failed I tried running the `docker run -p 27015:27015/udp avivace/ror2server:latest` command straight from the docs.  Both are giving me the same error, I've attached the server and client logs below.

Thanks!

<details>
<summary>Client log</summary>
<br>
<pre>
Parsed address=10.10.20.28 port=27015. Setting desired host.
GameNetworkManager.desiredHost={ hostType=IPv4 address=10.10.20.28 port=27015 }
Attempting connection. ip=10.10.20.28 port=27015
<color=#FFFF00>The prefab 'ArenaMissionController' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.</color>
<color=#FFFF00>Attempt to send to not connected connection {1}</color>
<color=#FF0000>Failed to send internal buffer channel:6 bytesToSend:1096</color>
<color=#FF0000>Send Error: WrongConnection channel:6 bytesToSend:1096</color>
ChannelBuffer SendBytes no space on unreliable channel 6
<color=#FFFF00>Attempt to send to not connected connection {1}</color>
<color=#FF0000>Failed to send internal buffer channel:6 bytesToSend:1096</color>
<color=#FF0000>Send Error: WrongConnection channel:6 bytesToSend:1096</color>
ChannelBuffer SendBytes no space on unreliable channel 6
<color=#FFFF00>Attempt to send to not connected connection {1}</color>
<color=#FF0000>Failed to send internal buffer channel:6 bytesToSend:1096</color>
<color=#FF0000>Send Error: WrongConnection channel:6 bytesToSend:1096</color>
ChannelBuffer SendBytes no space on unreliable channel 6
</pre>
</details>

<details>
<summary>Serverlog</summary>
<br>
<pre>
Updating Risk of Rain 2 server...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Downloading update (22 of 51663 KB)...
[  0%] Downloading update (2117 of 51663 KB)...
[  4%] Downloading update (4519 of 51663 KB)...
[  8%] Downloading update (6238 of 51663 KB)...
[ 12%] Downloading update (7876 of 51663 KB)...
[ 15%] Downloading update (9298 of 51663 KB)...
[ 17%] Downloading update (10758 of 51663 KB)...
[ 20%] Downloading update (12193 of 51663 KB)...
[ 23%] Downloading update (13554 of 51663 KB)...
[ 26%] Downloading update (15159 of 51663 KB)...
[ 29%] Downloading update (16582 of 51663 KB)...
[ 32%] Downloading update (18073 of 51663 KB)...
[ 34%] Downloading update (19464 of 51663 KB)...
[ 37%] Downloading update (20929 of 51663 KB)...
[ 40%] Downloading update (22507 of 51663 KB)...
[ 43%] Downloading update (23947 of 51663 KB)...
[ 46%] Downloading update (25429 of 51663 KB)...
[ 49%] Downloading update (26820 of 51663 KB)...
[ 51%] Downloading update (28248 of 51663 KB)...
[ 54%] Downloading update (29808 of 51663 KB)...
[ 57%] Downloading update (30895 of 51663 KB)...
[ 59%] Downloading update (32106 of 51663 KB)...
[ 62%] Downloading update (32926 of 51663 KB)...
[ 63%] Downloading update (33653 of 51663 KB)...
[ 65%] Downloading update (34348 of 51663 KB)...
[ 66%] Downloading update (35078 of 51663 KB)...
[ 67%] Downloading update (35881 of 51663 KB)...
[ 69%] Downloading update (36617 of 51663 KB)...
[ 70%] Downloading update (37343 of 51663 KB)...
[ 72%] Downloading update (38059 of 51663 KB)...
[ 73%] Downloading update (38882 of 51663 KB)...
[ 75%] Downloading update (39603 of 51663 KB)...
[ 76%] Downloading update (40347 of 51663 KB)...
[ 78%] Downloading update (41062 of 51663 KB)...
[ 79%] Downloading update (41837 of 51663 KB)...
[ 80%] Downloading update (42573 of 51663 KB)...
[ 82%] Downloading update (43319 of 51663 KB)...
[ 83%] Downloading update (44163 of 51663 KB)...
[ 85%] Downloading update (44941 of 51663 KB)...
[ 86%] Downloading update (45700 of 51663 KB)...
[ 88%] Downloading update (46497 of 51663 KB)...
[ 90%] Downloading update (47264 of 51663 KB)...
[ 91%] Downloading update (48048 of 51663 KB)...
[ 93%] Downloading update (48801 of 51663 KB)...
[ 94%] Downloading update (49541 of 51663 KB)...
[ 95%] Downloading update (50254 of 51663 KB)...
[ 97%] Downloading update (51054 of 51663 KB)...
[ 98%] Downloading update (51663 of 51663 KB)...
[100%] Downloading update (51663 of 51663 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
"@sSteamCmdForcePlatformType" = "windows"
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 62.02 (398320712 / 642228757)
Success! App '1180760' fully installed.
Generating server configuration...
Generating initial Wine configuration...
wine: created the configuration directory '/home/steam/.wine'
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0012:err:ole:get_local_server_stream Failed: 80004002
0014:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0014:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
0014:err:ole:get_local_server_stream Failed: 800736b7
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0016:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0016:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0018:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0018:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not load wine-gecko. HTML rendering will be disabled.
0027:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0027:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0029:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0029:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/steam/.wine' has been updated.
002d:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
002d:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Let's wait :)
Starting server...
Mono path[0] = 'Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Managed'
Mono config path = 'Z:/home/steam/ror2-dedicated/MonoBleedingEdge/etc'
002d:fixme:win:EnumDisplayDevicesW ((null),0,0x22f220,0x00000000), stub!
002d:fixme:win:EnumDisplayDevicesW (L"\\\\.\\DISPLAY1",0,0x22f220,0x00000000), stub!
002d:fixme:win:EnumDisplayDevicesW ((null),1,0x22f220,0x00000000), stub!
Initialize engine version: 2018.4.18f1 (61fce66342ad)
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.314 seconds
WARNING: Shader Unsupported: 'Hidden/PostProcessing/DepthOfField' - Pass 'CoC Calculation' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/DepthOfField' - Pass 'CoC Calculation' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/DepthOfField' - Setting to default shader.
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11]' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11]' - Pass 'FORWARDADD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11]' - All passes removed
WARNING: Shader Unsupported: 'Hidden/PostProcessing/ScreenSpaceReflections' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/ScreenSpaceReflections' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Uber' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/LightMeter' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/LightMeter' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/Vectorscope' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/Vectorscope' - Setting to default shader.
WARNING: Shader Unsupported: 'Hopoo Games/FX/Cloud Remap' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Hopoo Games/FX/Cloud Remap' - All passes removed
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/Waveform' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/Waveform' - Setting to default shader.
WARNING: Shader Unsupported: 'Hopoo Games/FX/Cloud Intersection Remap' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'Hopoo Games/FX/Cloud Intersection Remap' - All passes removed
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hopoo Games/FX/Cloud Intersection Remap' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/PostProcessing/FinalPass' - Pass '' has no vertex shader
WARNING: Shader Unsupported: 'Hidden/PostProcessing/CopyStdFromTexArray' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/CopyStdFromTexArray' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/PostProcessing/MultiScaleVO' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/MultiScaleVO' - Setting to default shader.
WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/Histogram' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hidden/PostProcessing/Debug/Histogram' - Setting to default shader.
UnloadTime: 1.899000 ms
EntryPointNotFoundException: GetCurrentProcessId
  at (wrapper managed-to-native) FlashWindow.GetCurrentProcessId()
  at FlashWindow..cctor () [0x00000] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
Rethrow as TypeInitializationException: The type initializer for 'FlashWindow' threw an exception.

 
(Filename: <168df4f4cd2d4334b6616d6d8d92d002> Line: 0)

Network message MsgType.Highest + 22 is unregistered.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/libc
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/libc.dll
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/libc
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/libc
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/libc.dll
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/libc
002d:fixme:wbemprox:client_security_SetBlanket 0x7f8c0a5260d0, 0x13a729a0, 10, 0, (null), 3, 3, (nil), 0x00000000
002d:fixme:wbemprox:client_security_Release 0x7f8c0a5260d0
002d:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
002d:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/data-0000000013D8C8D0.dll
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/data-0000000013DF3310.dll
Fallback handler could not load library Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Mono/data-000000000AA22030.dll
002d:fixme:win:RegisterDeviceNotificationW (hwnd=0x20042, filter=0x13d040f0,flags=0x00000000) returns a fake device notification handle!
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:win:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002d:fixme:bthpropscpl:BluetoothFindFirstDevice (0x22d320 0x13e8d7b0): stub!
Searching for compatible XInput library...

 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

002d:fixme:xinput:XInputGetState (index 255, state 0x2bb7c20) Stub!
002d:fixme:xinput:XInputGetStateEx (index 255, state 0x22d740) Stub!
Found Xinput1_4.dll.

 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

EntryPointNotFoundException: AttachConsole
  at (wrapper managed-to-native) RoR2.Console.AttachConsole(int)
  at RoR2.Console.SetupSystemConsole () [0x0006c] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
  at RoR2.Console.Awake () [0x00006] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
RoR2.RoR2Application:OnLoad()
RoR2.RoR2Application:Awake()
 
(Filename: <168df4f4cd2d4334b6616d6d8d92d002> Line: 0)

Initializing system: ArtifactCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: BadClientEntityStateMachineFix
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: BodyCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: BuffCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unregistered buff CrocoRegen!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unregistered buff MercExpose!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unregistered buff BodyArmor!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: CostTypeCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: GameEndingCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: EffectCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Error registering effect "DroneFlamethrowerEffect (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Error registering effect "FireMeatBallPool (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Error registering effect "LunarWispTrackingBombExp_Prf (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Error registering effect "LunarWispMinigunChargeUp (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Error registering effect "SiphonTetherHealing (UnityEngine.GameObject)": Prefab does not have EffectComponent attached.
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: EliteCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: EquipmentCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: FileIoIndicatorManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: DebugOverlay
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: GenericPickupController
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: NetworkUIPromptController
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: PickupDropletController
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: RunArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: ItemCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: Language
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Found icon.png
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Setting current language to "en"
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: MasterCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: MusicTrackCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: PickupCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: PickupTransmutationManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: ProjectileCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: RuleCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: SceneCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Shader 'CalmWater/Calm Water [DX11] [Double Sided]': fallback shader 'Legacy/Diffuse' not found
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARDBACK' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Pass 'FORWARD' has no vertex shader
WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - All passes removed
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'CalmWater/Calm Water [DX11] [Double Sided]' - Setting to default shader.
Initializing system: SkinCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: SurvivorCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Unregistered survivor Bandit!
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: UnlockableCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: UserProfile
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: StatDef
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: StatManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: StatSheet
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: SkillCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: EnemyInfoPanel
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: UILayerKey
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: NetworkSoundEventCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: BombArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: CommandArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: DoppelgangerInvasionManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: EnigmaArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: FriendlyFireArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: MonsterTeamGainsItemsArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: SacrificeArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: SwarmsArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: TeamDeathArtifactManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: NetworkExtensions
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: AchievementManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: ArtifactMask
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: LunarItemOrEquipmentCostTypeHelper
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: ItemDisplayRuleSet
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: PreGameRuleVoteController
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: ShrineCleanseBehavior
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: GameModeCatalog
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Registered gamemode BaseDefenseRun True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Registered gamemode ClassicRun True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Registered gamemode EclipseRun True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Registered gamemode WeeklyRun True
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: Loadout
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: BodyLoadoutManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: ProjectileGhostReplacementManager
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: RuleBook
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: SerializableLoadout
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: SteamworksLobbyDataGenerator
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: LogBookController
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Initializing system: CharacterSpawnCard
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

WARNING: Shader Unsupported: 'Hopoo Games/Internal/Outline Highlight' - Pass '' has no vertex shader
ERROR: Shader Shader is not supported on this GPU (none of subshaders/fallbacks are suitable)WARNING: Shader Unsupported: 'Hopoo Games/Internal/Outline Highlight' - Setting to default shader.
Active scene changed from  to splash
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Loaded scene splash loadSceneMode=2
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

NullReferenceException: Object reference not set to an instance of an object
  at RoR2.Console.FindConVar (System.String name) [0x00000] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
  at RoR2.Console.RunCmd (RoR2.Console+CmdSender sender, System.String concommandName, System.Collections.Generic.List`1[T] userArgs) [0x00035] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
  at RoR2.Console.SubmitCmd (RoR2.Console+CmdSender sender, System.String cmd, System.Boolean recordSubmit) [0x000b2] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
  at RoR2.Console.SubmitCmd (RoR2.NetworkUser sender, System.String cmd, System.Boolean recordSubmit) [0x00007] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
  at RoR2.SplashScreenController.Finish () [0x0000b] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
  at UnityEngine.Events.InvokableCall.Invoke () [0x00011] in <7cd45074592849c798ee04bb333cbf3a>:0 
  at UnityEngine.Events.UnityEvent.Invoke () [0x00023] in <7cd45074592849c798ee04bb333cbf3a>:0 
  at RoR2.OnEnableEvent.OnEnable () [0x00000] in <168df4f4cd2d4334b6616d6d8d92d002>:0 
UnityEngine.GameObject:SetActive(Boolean)
UnityEngine.Timeline.ActivationMixerPlayable:ProcessFrame(Playable, FrameData, Object)
 
(Filename: <168df4f4cd2d4334b6616d6d8d92d002> Line: 0)
</pre>
</details>

**Comment by avivace** [comment]
Thanks for the heads up @RSLak1 ! Adding it to the FAQ.
