### ISSUE TITLE
Docker image size is quite large - install the game as part of entry.sh?

### ISSUE THREAD

**Issue by Half-Shot** [avivace/ror2-server#21]
The docker image is around ~1GB which is a bit of big one, especially when running locally for testing and removing the containers afterwards. There are also probably some legal issues around bundling the game content inside the Docker image, so it might be better to wait until the container has started before installing the game files?

I see that you update the game in entry.sh anyway, so it might be better to do it this way?

**Comment by fnicolini** [comment]
That's a good idea, thanks for the feedback. Changes have already been merged.
