### ISSUE TITLE
Run local server via localtunnel or similar

### ISSUE THREAD

**Issue by loscil06** [avivace/ror2-server#25]
Subject, is it possible?
Thanks for the hard work!

**Comment by avivace** [comment]
Hi @loscil06 ! Can you provide more information about "localtunnel"? What are you trying to accomplish?

**Comment by loscil06** [comment]
A very common tool, eg. localtunnel, ngrok.
Basically you run the software, specify the port and tada: you have a server accessible tru the internet without having to fiddle around switches, port forwarding or even breaching tru NATs.

**Comment by mchobbylong** [comment]
YES you can. Just make sure that your port forwarding tool supports UDP forwarding, and be careful to the firewall settings on your VPS.

**Comment by avivace** [comment]
Thanks @mchobbylong ! @loscil06 Looks like you can do that, please re-open this issue if you have other questions :)
