### ISSUE TITLE
Server not shown in server list.

### ISSUE THREAD

**Issue by RestlessRabbits** [avivace/ror2-server#31]
I tried different approaches and checked that I can indeed connect to the server.
The server I execute the following command on is - whenever I run this - an exposed host - for testing purposes:

docker run -p 27015:27015/udp avivace/ror2server:latest

When all is done, I can connect to the server via ingame console and the connect command using the ip and port 27015.
I also get a good response from 
What does not work is getting it listed as a server - neither ingame nor within the server list of the steam client.
I also added the plain ip, the ip with port 27015 and the ip with port 27016 to my favorites.
The server windows does not list it and inside of the favorites I get the message that the server does not answer.

The api call gives me the following output:
![ror2](https://user-images.githubusercontent.com/28935071/157400140-cd06376a-e102-4d41-988b-14b6ba427196.png)

I also downloaded the dockerfile and added 
ENV WINEDEBUG=fixme-all
to have less errors displayed.

Any ideas what could be causing the server being available to be connected directly to, but not being listed?
Of course the heartbeat is set to 1.
The system where docker is running is Ubunto 20.04.

Any ideas and help appreciated :)
I will test your inputs ;)

**Comment by dubvulture** [comment]
As the README says:
- `R2_HEARTBEAT`, set to `1` to **advertise to the master server and list your server** in the internal server browser. If you enable this, add `-p 27016:27016/udp` to your Docker command;

So you should run:
```
docker run -p 27015:27015/udp -p 27016:27016/udp -e R2_HEARTBEAT=1 avivace/ror2server:latest
```

**Comment by RestlessRabbits** [comment]
I've set the envoirement vars in my dockerfile to a fixed value therefore I didn't add the hearbeat as -e.
As mentioned I added **ENV WINEDEBUG=fixme-all** to have less error messages - which is fine for me so far.

Interrestingly:
` docker run -p 27015:27015/udp -p 27016:27016/udp -e R2_HEARTBEAT=1 avivace/ror2server:latest`
**works perfect**

` docker run -p 27015:27015/udp -p 27016:27016/udp avivace/ror2server:latest`
**does not work** even while I have the R2_HEARTBEAT=1 fixed in my dockerfile when I build that image locally.

I assume the port order AND the env did the trick.
Thank you very much.

**Comment by avivace** [comment]
> I've set the envoirement vars in my dockerfile to a fixed value therefore I didn't add the hearbeat as -e. As mentioned I added **ENV WINEDEBUG=fixme-all** to have less error messages - which is fine for me so far.
> 
> Interrestingly: ` docker run -p 27015:27015/udp -p 27016:27016/udp -e R2_HEARTBEAT=1 avivace/ror2server:latest` **works perfect**
> 
> ` docker run -p 27015:27015/udp -p 27016:27016/udp avivace/ror2server:latest` **does not work** even while I have the R2_HEARTBEAT=1 fixed in my dockerfile when I build that image locally.
> 
> I assume the port order AND the env did the trick. Thank you very much.



> I've set the envoirement vars in my dockerfile to a fixed value therefore I didn't add the hearbeat as -e. As mentioned I added **ENV WINEDEBUG=fixme-all** to have less error messages - which is fine for me so far.
> 
> Interrestingly: ` docker run -p 27015:27015/udp -p 27016:27016/udp -e R2_HEARTBEAT=1 avivace/ror2server:latest` **works perfect**
> 
> ` docker run -p 27015:27015/udp -p 27016:27016/udp avivace/ror2server:latest` **does not work** even while I have the R2_HEARTBEAT=1 fixed in my dockerfile when I build that image locally.
> 
> I assume the port order AND the env did the trick. Thank you very much.

I don't think the order is relevant here. `docker run` will pull the image published on docker hub and still use the default Dockerfile with `R2_HEARTBEAT=0`, as long as you don't actually build it yourself and exactly tag/name it as "avivace/ror2server:latest"..
