### ISSUE TITLE
After I open the console and input the command, why do the following problems occur 

### ISSUE THREAD

**Issue by snow-man9** [avivace/ror2-server#33]
After I open the console and input the command, why do the following problems occur     connect "<SERVER_IP>:27015";

The prefab 'ArenaMissionController' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
The prefab 'Moon2DropshipZone' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
The prefab 'HOLDER_ Gauntlets' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
The prefab 'VoidCamp' has multiple NetworkIdentity components. There can only be one NetworkIdentity on a prefab, and it must be on the root object.
UNet Client Error Connect Error: 11

**Comment by avivace** [comment]
Which command are you running to start up the server?
