### ISSUE TITLE
it doesn't seem to work with players more than 4, despite adding the environment variable 

### ISSUE THREAD

**Issue by aimen08** [avivace/ror2-server#36]
hello, i like the ease of use when it comes to this server, everything works well,
this is the command i'm using
`docker run -p 27015:27015/udp -p 27016:27016/udp -e R2_PSW='autism' -e R2_PLAYERS=16 -e R2_HEARTBEAT=1 -e R2_HOSTNAME='Autism Nation' avivace/ror2server:latest`

the server appears with 16 players but it wont work with more than 4.
![image](https://user-images.githubusercontent.com/32209952/164123905-3d805b54-19bc-4b89-bf15-91e911684fb8.png)

please help.

**Comment by avivace** [comment]
> hello, i like the ease of use when it comes to this server, everything works well, this is the command i'm using `docker run -p 27015:27015/udp -p 27016:27016/udp -e R2_PSW='autism' -e R2_PLAYERS=16 -e R2_HEARTBEAT=1 -e R2_HOSTNAME='Autism Nation' avivace/ror2server:latest`
> 
> the server appears with 16 players but it wont work with more than 4. ![image](https://user-images.githubusercontent.com/32209952/164123905-3d805b54-19bc-4b89-bf15-91e911684fb8.png)
> 
> please help.

Hey! Thanks for the heads up, I think you are right and we're missing an additional setting required to allow more than 4 players in a lobby.

Can you try the `morethan4players-fix` branch and see if that works for you?

**Comment by aimen08** [comment]
no still nothing , the server.cfg inside the docker image shows the additional setting, but still same problem ,
![image](https://user-images.githubusercontent.com/32209952/164188942-6ff3e9e2-5fd0-4c0e-b282-a0bba6e3a781.png)

this is the error that appears when the 5th person try to login from console 
![image](https://user-images.githubusercontent.com/32209952/164189073-529697e7-15d9-4c36-a7d3-8752ce21ef98.png)

**Comment by avivace** [comment]
> no still nothing , the server.cfg inside the docker image shows the additional setting, but still same problem ,
> 
> ![image](https://user-images.githubusercontent.com/32209952/164188942-6ff3e9e2-5fd0-4c0e-b282-a0bba6e3a781.png)
> 
> this is the error that appears when the 5th person try to login from console
> 
> ![image](https://user-images.githubusercontent.com/32209952/164189073-529697e7-15d9-4c36-a7d3-8752ce21ef98.png)

Can you try :

```
# clone this repository
git clone https://github.com/avivace/ror2-server/
# checkout to 
git checkout morethan4players-fix
# build docker image 
docker build . -t fixmulti
# run it with your desired settings
docker run -p 27015:27015/udp -p 27016:27016/udp -e R2_PSW='autism' -e R2_PLAYERS=16 -e R2_HEARTBEAT=1 -e R2_HOSTNAME='Autism Nation' fixmulti
```

**Comment by avivace** [comment]
@aimen08 any news on this?

**Comment by aimen08** [comment]
@avivace hello, just didn't get 5 people to test this yet, we are currently 4 . i will update when then the 5th person test it.

**Comment by avivace** [comment]
> @avivace hello, just didn't get 5 people to test this yet, we are currently 4 . i will update when then the 5th person test it.

Great! Thanks :pray:

**Comment by lu0se** [comment]
It may be the official problem.When you dedicated server on windows,it doesn't work with players more than 4,we should submit this problem to official developer.

**Comment by xxxsen** [comment]
fixmulti branch still not ok, got error like this

```log
<color=#FF0000>UNet Client Disconnect Error: NoResources</color>
NetworkManagerSystem.desiredHost={ hostType=None }
<color=#FF0000>ClientDisconnected due to error: NoResources</color>
```

**Comment by LittleKingDW** [comment]
Can confirm that this is still an issue, any more than 4 are booted with the no resources error, even with the fixmulti branch.

**Comment by avivace** [comment]
I looked this up a bit, and I couldn't find any time where more than 4 players were ever supported without a mod, so I guess it's just a visual value, but has no real effect. I'm closing this till we have new information.

**Comment by sbblg** [comment]
sv_maxplayers 16; 
steam_lobby_max_members 16;
My server is run in Windows System.It need two
