### ISSUE TITLE
Always prompt "002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!"

### ISSUE THREAD

**Issue by shuaidemeikan** [avivace/ror2-server#39]
Always prompt "002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!"，server, and the server cannot connect
I tried two different Linux distributions, Debian 10 and CentOS 8，and the result was that I kept brushing this prompt，The following is the specific output information
Installing Risk of Rain 2 server...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Downloading update (0 of 54,887 KB)...
[  0%] Downloading update (30 of 54,887 KB)...
[  0%] Downloading update (258 of 54,887 KB)...
[  0%] Downloading update (626 of 54,887 KB)...
[  1%] Downloading update (1,054 of 54,887 KB)...
[  1%] Downloading update (1,410 of 54,887 KB)...
[  2%] Downloading update (1,858 of 54,887 KB)...
...
[ 99%] Downloading update (54,887 of 54,887 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1648077083
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Please use force_install_dir before logon!
"@sSteamCmdForcePlatformType" = "windows"
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x11) preallocating, progress: 77.63 (1742385383 / 2244404447)
 Update state (0x61) downloading, progress: 0.34 (7534305 / 2244404447)
 Update state (0x61) downloading, progress: 1.91 (42842274 / 2244404447)
 Update state (0x61) downloading, progress: 4.07 (91345380 / 2244404447)
 Update state (0x61) downloading, progress: 5.46 (122432967 / 2244404447)
...
 Update state (0x81) verifying update, progress: 79.19 (1777378638 / 2244404447)
 Update state (0x81) verifying update, progress: 93.02 (2087778309 / 2244404447)
 Update state (0x101) committing, progress: 100.00 (2244404447 / 2244404447)
Success! App '1180760' fully installed.
Generating server configuration...
Generating initial Wine configuration...
wine: created the configuration directory '/home/steam/.wine'
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0014:err:ole:get_local_server_stream Failed: 80004002
0012:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0012:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 183
0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
0012:err:ole:get_local_server_stream Failed: 800736b7
0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0016:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0016:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0018:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0018:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not find Wine Gecko. HTML rendering will be disabled.
0025:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0025:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
0027:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0027:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Could not find Wine Gecko. HTML rendering will be disabled.
wine: configuration in L"/home/steam/.wine" has been updated.
0036:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0036:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Let's wait :)
Starting server...
Mono path[0] = 'Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/Managed'
Mono config path = 'Z:/home/steam/ror2-dedicated/MonoBleedingEdge/etc'
002c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
Initialize engine version: 2019.4.26f1 (e0392c6b2363)
[Subsystems] Discovering subsystems at path Z:/home/steam/ror2-dedicated/Risk of Rain 2_Data/UnitySubsystems
Forcing GfxDevice: Null
GfxDevice: creating device client; threaded=0
NullGfxDevice:
    Version:  NULL 1.0 [1.0]
    Renderer: Null Device
    Vendor:   Unity Technologies
Begin MonoManager ReloadAssembly
- Completed reload, in  0.813 seconds
Microsoft Media Foundation video decoding to texture disabled: graphics device is Null, only Direct3D 11 and Direct3D 12 (only on desktop) are supported.
UnloadTime: 1.618800 ms
Network message MsgType.Highest + 22 is unregistered.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

buildId = 1.2.3.1
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Active scene changed from  to loadingbasic
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Loaded scene loadingbasic loadSceneMode=2
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Couldn't create a Convex Mesh from source mesh "rock2ModularMesh" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)

application data path isZ:/home/steam/ror2-dedicated/Risk of Rain 2_Data
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

002c:fixme:wbemprox:client_security_SetBlanket 000000006662DCF0, 00007F7B1B4C7D50, 10, 0, (null), 3, 3, 0000000000000000, 0x00000000
002c:fixme:wbemprox:client_security_Release 000000006662DCF0
002c:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
002c:fixme:wbemprox:wbem_services_CreateInstanceEnum unsupported flags 0x00000030
002c:fixme:win:RegisterDeviceNotificationW (hwnd=0x2003a, filter=0x7f7b123c3f00,flags=0x00000000) returns a fake device notification handle!
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
002c:fixme:bthpropscpl:BluetoothFindFirstDevice (000000000021CC60 00007F7B1260AA20): stub!
002c:fixme:setupapi:CM_Get_Parent 000000000021CA90 0x00000000 0x00000000 stub
PlatformSystems:InitNetworkManagerSystem
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

002c:fixme:sync:NtQueryTimerResolution (0x21dc88,0x21dc80,0x21dc78), stub!
Launch Parameters:
  arg[0]="Z:\home\steam\ror2-dedicated\Risk of Rain 2.exe"

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not load config /Config/config.cfg: Could not find file "Z:\home\steam\ror2-dedicated\Risk of Rain 2_Data\Config\config.cfg"
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Could not load config /Config/autoexec.cfg: Could not find file "Z:\home\steam\ror2-dedicated\Risk of Rain 2_Data\Config\autoexec.cfg"
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Cannot call LocalUserManager.SetLocalUsers at this time, user login changes are not safe at this time.
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Loading custom server configuration...
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Hosting server...
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

NetworkManagerSystem.desiredHost={ hostType=Self listen=True maxPlayers=4 }
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

LoadContentPacks() start
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
0048:fixme:setupapi:CM_Get_Parent 0000000067EFF010 0x00000000 0x00000000 stub
0048:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
0048:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
0048:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
0048:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x2100 for device 0.
0048:fixme:bthpropscpl:BluetoothFindFirstDevice (0000000067EFF010 00007F7B1260AA20): stub!
0048:fixme:setupapi:CM_Get_Parent 0000000067EFEE40 0x00000000 0x00000000 stub
002c:fixme:rawinput:RegisterRawInputDevices Unhandled flags 0x100 for device 0.
Couldn't create a Convex Mesh from source mesh "mdlRailGunnerBasicMine" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)

002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
Couldn't create a Convex Mesh from source mesh "VoidRaidCrabCollision_head" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)

002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
Couldn't create a Convex Mesh from source mesh "BBBoulderMediumRound1" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)

002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
Couldn't create a Convex Mesh from source mesh "meshSulfurPodTop" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
(Filename:  Line: 91)

002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices devices 0x7f7b1204d3a0, device_count 0x21e940, size 16 stub!
002c:fixme:rawinput:GetRegisteredRawInputDevices dev

**Comment by avivace** [comment]
I don't think this is related to the way we deploy the server, it's just RoR2 code.
