### ISSUE TITLE
Installing mods

### ISSUE THREAD

**Issue by jwilling** [avivace/ror2-server#4]
First of all, thanks for the project. I love how easy it is to spin up a quick dedicated server!

I’m interested in installing some mods. I wonder what the best way is to do this with this image. Maybe the mods folder could be exposed as a volume?

**Comment by Coolfeather2** [comment]
Just include the volume in your run command or docker-compose
eg. `docker run avivace/ror2server:0.1 -p 27015:27015/udp -v $HOST_DIR:/home/steam/ror2-dedicated/BepInEx`

**Comment by jwilling** [comment]
You’re right, that totally should work. Thanks!

**Comment by dubvulture** [comment]
Reopening this issue since mods are not working.

The problem seems to arise from wine DLL override [behaviour](https://github.com/BepInEx/BepInEx/issues/52#issuecomment-433602459).
[Here](https://bepinex.github.io/bepinex_docs/master/articles/advanced/steam_interop.html?tabs=tabid-1#protonwine)'s the recommended fix, but it requires using the `winecfg` gui.

I am currently trying to understand how to translate all that into bash commands.

**Comment by dubvulture** [comment]
I tried fiddling with wine by modifying the [command](https://github.com/avivace/ror2-server/blob/7ffa5167784f7852edf2c4eb9e53e5aa0944044c/entry.sh#L16) used to start the server.

- `WINEDLLOVERRIDES="winhttp=n,b" xvfb-run /opt/wine-stable/bin/wine "${STEAMAPPDIR}/Risk of Rain 2.exe"`
    - prefer native libraries, wine builtin after
    - nothing different happens
    - `WINEDEBUG=+loaddlls` shows both native and builtin `winhttp.dll` being loaded in said order (why twice? I don't know)
- `WINEDLLOVERRIDES="winhttp=n" xvfb-run /opt/wine-stable/bin/wine "${STEAMAPPDIR}/Risk of Rain 2.exe"`
    - prefer native libraries, ignore wine builtin
    - stuck after "Starting server...", nothing happens after that
    - `WINEDEBUG=+loaddlls` shows that it is indeed trying to do something, but instead of loading UnityPlayer.dll & jsproxy.dll & winhttp.dll (builtin) it is instead loading UnityPlayer & winex11.drv & usp10.dll and then getting stuck
- `WINEDLLOVERRIDES="winhttp=" xvfb-run /opt/wine-stable/bin/wine "${STEAMAPPDIR}/Risk of Rain 2.exe"`
    - Disables both native libraries and wine builtin
    - Fails to load `winhttp.dll` (as expected, but I tested anyway)

In the end, I am left with more questions than answers:
- `nb-mode` - why is it loading winhttp.dll both times, and if it is intended, why is Doorstop not being executed?
- `n-mode` - why is it loading [usp10.dll](https://en.wikipedia.org/wiki/Uniscribe) which is never loaded in `nb-mode`, and why is it getting stuck?

**Comment by dubvulture** [comment]
PR #10 should have fixed mods support. 
Checkout the new README for instructions and let me know if there are any problems or questions.

**Comment by jwilling** [comment]
@dubvulture You're awesome, thank you!

**Comment by avivace** [comment]
@dubvulture Rad! You rock!
