### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by AmirrezaKN** [avivace/ror2-server#40]
Hey there
I'm trying to run the docker with your default command for it and getting this in the logs

```
Installing Risk of Rain 2 server...
Redirecting stderr to '/root/.steam/logs/stderr.txt'
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
src/tier0/threadtools.cpp (1804) : Thread synchronization object is unuseable
[  0%] Checking for available updates...
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
Installing Risk of Rain 2 server...
Redirecting stderr to '/root/.steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
src/tier0/threadtools.cpp (1804) : Thread synchronization object is unuseable
[  0%] Checking for available updates...
src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
Thread failed to initialize
```

the os is Centos 9
what is the problem here?

**Comment by avivace** [comment]
> Hey there I'm trying to run the docker with your default command for it and getting this in the logs
> 
> ```
> Installing Risk of Rain 2 server...
> Redirecting stderr to '/root/.steam/logs/stderr.txt'
> src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
> Thread failed to initialize
> src/tier0/threadtools.cpp (1804) : Thread synchronization object is unuseable
> [  0%] Checking for available updates...
> src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
> Thread failed to initialize
> Installing Risk of Rain 2 server...
> Redirecting stderr to '/root/.steam/logs/stderr.txt'
> Looks like steam didn't shutdown cleanly, scheduling immediate update check
> src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
> Thread failed to initialize
> src/tier0/threadtools.cpp (1804) : Thread synchronization object is unuseable
> [  0%] Checking for available updates...
> src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
> Thread failed to initialize
> ```
> 
> the os is Centos 9 what is the problem here?

Are you sure you have enough disk space available?
