### ISSUE TITLE
[Compatibility] Upstream steamcmd docker image upgraded to Debian 11

### ISSUE THREAD

**Issue by mchobbylong** [avivace/ror2-server#45]
Since upstream docker image is upgraded to Debian 11 (bullseye), there are two issues in this repo:

- Wine emulator needs to upgrade to versions for Debian 11 (currently for Debian 10)
- `steamcmd` reported [compatibility issue](https://github.com/ValveSoftware/steam-for-linux/issues/8083) on Debian 11, which causes crashing (and I just verified it, it still happens)

**Comment by dubvulture** [comment]
I'm pretty sure we're already using a steamcmd image with ubuntu 20.04 as the base OS.
See [here](https://github.com/avivace/ror2-server/blob/e1581efa000f57bd9b4075168f3e975e3e12d568/Dockerfile#L4)
```
FROM steamcmd/steamcmd:ubuntu-20
```

This change was quite "recent" (7 months ago), so maybe you're working on an older fork of this repo.

**Comment by mchobbylong** [comment]
Ah yes, I was not aware of that. Closed.
